version: "3.9"

services:
  app:
    env_file:
    - ".env"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /data/elementary-bounties/:/app/data/
    ports:
      - "5000:5000"  # Map host port 8000 to container port 8000
