"""completed is now state

Revision ID: 3960abf8cbad
Revises: 7c187359b8d6
Create Date: 2025-01-06 19:18:55.936527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3960abf8cbad'
down_revision = '7c187359b8d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=False))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
