"""issue number is now just number

Revision ID: 82a1e9406037
Revises: 3960abf8cbad
Create Date: 2025-01-06 21:48:48.046331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a1e9406037'
down_revision = '3960abf8cbad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.drop_column('issue_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_number', sa.INTEGER(), nullable=False))
        batch_op.drop_column('number')

    # ### end Alembic commands ###
