"""add repository_name to issue

Revision ID: e8a62b3e2c01
Revises: 9350d16deefc
Create Date: 2025-02-02 22:25:33.142288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a62b3e2c01'
down_revision = '9350d16deefc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('repository_name')

    # ### end Alembic commands ###
