name: Lint

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry sync --all-groups --no-root
    - name: Pylint
      run: |
        poetry run pylint ./
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: check