name: Lint

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Ruff
      uses: astral-sh/ruff-action@v3.0.1
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: check